import './globals.css'
import './preflight.css'
import type { Metadata } from 'next'
import { PT_Sans } from 'next/font/google'
import React from "react";
import header from './header.module.css'
import siteLogoUrl from 'public/logo/HIDDEN COLOR.svg'
import davinciLogoUrl from 'public/logo/DaVinci-Resolve-Logo-1.webp'
import Image from "next/image";
import Link from 'next/link'


const ptSans = PT_Sans({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-ptsans',
})

export const metadata: Metadata = {
  title: 'My color blog',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={ptSans.variable}>
      <div className='main__container'>
          <header className={header.container}>
              <Image
                  src={siteLogoUrl}
                  alt='Логотип сайты скрытый цвет'/>
              <nav className={header.nav}>
                <Link href='https://www.blackmagicdesign.com/' target='_blank'>
                    <Image
                        className={header.nav__davinciLogo}
                        src={davinciLogoUrl}
                        width={40}
                        height={40}
                        alt='Логотип сайты скрытый цвет'/>
                </Link>

            </nav>
          </header>
        {children}
      </div>
      </body>
    </html>
  )
}
