import './globals.css'
import './preflight.css'
import type { Metadata } from 'next'
import { PT_Sans } from 'next/font/google'
import React from "react";
import Header from "@/components/Header";



const ptSans = PT_Sans({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-ptsans',
})

export const metadata: Metadata = {
  title: 'My color blog',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body className={ptSans.variable}>

        <Header/>
        {children}

    </body>
    </html>
  )
}
